server:
  port: ${SERVER_PORT:5000}
  shutdown: graceful

spring:
  application:
    name: ${APP_NAME:ebguide}

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: never

logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
